# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        version: 12
    - name: Github Action for Yarn
      user: Borales/actions-yarn@2.1.0
      with:
        # yarn install command
        cmd: install # npn install/ yarn install

    - name: build yarn on github  # it build the yarn on github repo 
      run: yarn build
    
    - name: install surge on github
      run: npm install -g surge

    - name: installing surge
      run: surge ./build http://reactappbyparas.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
